set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(CMAKE_C_COMPILER   "${CROSS_COMPILE}gcc" CACHE STRING "C Compiler")
set(CMAKE_CXX_COMPILER "${CROSS_COMPILE}g++" CACHE STRING "C++ Compiler")
set(CMAKE_ASM_COMPILER "${CROSS_COMPILE}gcc" CACHE STRING "ASM Compiler")
set(CMAKE_AR           "${CROSS_COMPILE}ar" CACHE STRING "Archiver")
set(CMAKE_LINKER       "${CROSS_COMPILE}ld" CACHE STRING "Linker")

set(ARCH_COMMON_FLAGS 
)
string(REPLACE ";" " " ARCH_COMMON_FLAGS_STR "${ARCH_COMMON_FLAGS}")

set(CMAKE_C_FLAGS   "${ARCH_COMMON_FLAGS_STR} ${CMAKE_C_FLAGS}"  CACHE STRING "C Flags")
set(CMAKE_CXX_FLAGS "${ARCH_COMMON_FLAGS_STR} ${CMAKE_CXX_FLAGS}" CACHE STRING "CXX Flags")
set(CMAKE_ASM_FLAGS "${ARCH_COMMON_FLAGS_STR} ${CMAKE_ASM_FLAGS}" CACHE STRING "ASM Flags")