[package]
name = "kernelx"
version = "0.1.0"
edition = "2024"
build = "scripts/build.rs"

[features]
# default = ["lockdep", "log-info", "no-smp"]

log-warn  = []
log-info  = ["log-warn"]
log-debug = ["log-info"]
log-trace = ["log-debug"]
log-trace-syscall = []
log-syscall-cpu-time = []
warn-unimplemented-syscall = []

lockdep = []
spinlock-check = []
no-smp = []
nolock = ["no-smp"]
swap-memory = []
backtrace = []
watchdog = []
scheduler-time-debug = []
scheduler-block-reason-debug = ["scheduler-time-debug"]
map-manager-lock-debug = []
fanotify = []
virtio-block-page-cache = []
ext4-native-skip-crc32c-verify = []

kvm=[]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[dependencies]
buddy-slab-allocator = "=0.4.6"
buddy_system_allocator = { version = "0.9", default-features = false, features = ["use_spin"] }
spin = "0.9"
smallvec = { version = "1.13", default-features = false }
bitflags = "2.0"
virtio-drivers = "0.7.5"
cfg-if = "1.0"
fixedstr = {version="0.5", features=["no-alloc", "pub-tstr"]}
num_enum = { version = "0.5", default-features = false}
downcast-rs = { version = "2.0.1", default-features = false , features = ["sync"]}
device_tree_parser = "0.4.0"
fdt = { git = "https://github.com/LRache/fdt-rust.git"}
bitfield-struct = "0.8.0" 
bitvec = { version = "1.0.1" , default-features = false, features = ["alloc"] }
elf = { version = "0.8.0", default-features = false }
visionfive2-sd = { git = "https://github.com/os-module/visionfive2-sd.git", rev = "af75139" }
kernelx-derive = { path = "crates/kernelx-derive" }

[build-dependencies]
bindgen = "0.72.1"
cc = "1.0"

[lints.rust]
unused_must_use = "deny"
